services:
  - type: web
    name: college-tracker-api
    env: node
    buildCommand: cd backend && npm install && npm run build && cd dist && npm install --production
    startCommand: cd backend/dist && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://college-tracker-admin:4!mps0N4@devconnector.kjngi.mongodb.net/college-tracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true # Automatically generate a secure value
      - key: JWT_EXPIRE
        value: 24h
      - key: FRONTEND_URL
        value: https://college-tracker-app.netlify.app
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false # Will be set manually
      - key: EMAIL_PASSWORD
        sync: false # Will be set manually

    healthCheckPath: /
    autoDeploy: true
